version: '3'
services:
  app1:
    build:
      context: ./app1
    container_name: "app1"
    volumes:
      - ./app1:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - devops_network

  app2:
    build:
      context: ./app2
    container_name: "app2"
    volumes:
      - ./app2:/usr/src/app
    ports:
      - 3001:3001
    networks:
      - devops_network

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    volumes:
      - "./rabbitmq:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - devops_network

networks:
  devops_network:
    driver: bridge
